[package]
name = "imbibe"
version = "0.1.0"
edition = "2024"
publish = false

[profile.dev]
opt-level = 0
debug = true
incremental = true

[profile.release]
opt-level = 3
debug = false
lto = true
strip = "symbols"

[dependencies]
anyhow = "1"
async-graphql = "7"
async-graphql-axum = "7"
axum = "0.8"
chrono = "0.4"
bon = "3.5"
config = { version = "0.15", default-features = false, features = ["ron"] }
diesel = { version = "2", features = ["chrono", "postgres"] }
diesel-async = { version = "0.5", features = ["deadpool", "postgres"] }
futures = "0.3"
jiff = "0.2"
opentelemetry = "0.29"
opentelemetry-otlp = { version = "0.29", features = ["grpc-tonic"] }
opentelemetry_sdk = { version = "0.29", features = ["rt-tokio"] }
secrecy = { version = "0.10", features = ["serde"] }
serde = { version = "1", features = ["derive"] }
sha2 = "0.10"
tendermint = "0.40"
tendermint-rpc = { version = "0.40", features = ["websocket-client"] }
thiserror = "2"
tokio = { version = "1", features = ["full"] }
tracing = "0.1"
tracing-opentelemetry = "0.30"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
url = { version = "2", features = ["serde"] }
uuid = "1"
