[package]
name = "imbibe-macros"
version.workspace = true
edition = "2024"
repository.workspace = true
publish.workspace = true

[lints]
workspace = true

[lib]
proc-macro = true

[dependencies]
syn = { version = "2" }
quote = "1"
