[package]
name = "imbibe-querier"
version.workspace = true
edition.workspace = true
repository.workspace = true
publish.workspace = true

[lints]
workspace = true

[features]
default = []

[dependencies]
bon = { workspace = true }
imbibe-domain = { workspace = true }
imbibe-persistence = { workspace = true }
tracing = { workspace = true }
thiserror = { workspace = true }

